name: Contract analysis

on:
  push:
    branches: [ feature/add-vul-check ]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Install
        run: npm ci
      - name: Check lint
        run: ./node_modules/.bin/solhint contracts/**/*.sol
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://trailofbits/eth-security-toolbox
        with:
          entrypoint: bash
      - name: Install
        run: npm ci
      - name: Scan vulnerabilities
        run: slither .
