name: Contract analysis

on:
  push:
    branches: [ feature/add-vul-check ]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - name: Upload node_modules
        uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules

  lint-check:
    name: Check lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - name: Check lint
        run: ./node_modules/.bin/solhint contracts/**/*.sol

  vulnerabilities-scan:
    name: Scan vulnerabilities
    runs-on: ubuntu-latest
    container:
      image: trailofbits/eth-security-toolbox
      options: "--entrypoint=bash --user=root"
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - name: Download node_modules
        uses: actions/download-artifact@v3
        with:
          name: node_modules
      - name: Scan vulnerabilities
        run: slither .
