name: Contract analysis

on:
  push:
    branches: [ feature/add-vul-check ]

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm ci
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ github.sha }}

  lint-check:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: Check lint
        run: ./node_modules/.bin/solhint contracts/**/*.sol

  vulnerabilities-scan:
    runs-on: ubuntu-latest
    container:
      image: trailofbits/eth-security-toolbox
      options: "--entrypoint=bash --user=root"
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ github.sha }}
      - name: Scan vulnerabilities
        run: slither .
