name: Contract analysis

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  install:
    uses: ./.github/workflows/contract-install.yml

  vulnerabilities-scan:
    name: Scan vulnerabilities
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - id: slither
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        with:
          node-version: 16
          sarif: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
