name: Installation

on:
  workflow_call:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            cache-node-modules-
      - run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
