name: Installation

on:
  workflow_call:

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache-node-modules-analysis
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-
      - run: yarn install
        if: steps.cache-node-modules-analysis.outputs.cache-hit != 'true'
