name: Lint check

on:
  push:
    branches: [ feature/add-vul-check ]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install ethlint
        run: npm install -g ethlint
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: solium -d contracts/
